dataset : 'sydney'
image_dir : '/data/Sydney_captions/jpgs'
caption_path : '/data/Sydney_captions/dataset_jpg.json'
caption_val_path : 'annotations/captions_sydney_test.json'
start_from: 'log_sydney_non/9/model-best.pkl'
checkpoint_path: 'log_sydney_non/9'
start_from: 'log_sydney_2fc_cos/9/model-best.pkl'
checkpoint_path: 'log_sydney_2fc_cos/9'

vocab_path: './data/vocab_sydney.pkl'
#eval_size: 8

gpu: !!str 0
