dataset : 'sydney'
image_dir : '/data/Sydney_captions/jpgs'
caption_path : '/data/Sydney_captions/dataset_jpg.json'
caption_val_path : 'annotations/captions_sydney_val.json'
vocab_path: './data/vocab_sydney.pkl'
vgg_model_path : '/workspace/RSICD_classify/vgg19_finetune_sydney_10_1000.pkl'
num_classes : 7
batch_size: 8
pattern: 'truelabel'

#session: !!str 5
gpu: '3'